<a href="https://colab.research.google.com/github/riyarvv/End-to-End-Customer-Churn-ML-Pipeline/blob/main/notebooks/09_Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# End-to-End Customer Churn ML Pipeline

## Notebook 09 – Feature Engineering

### Objective

Create new features, organize reusable code into Python modules, and prepare the cleaned dataset for machine learning.

In [54]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [55]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

In [56]:
df = pd.read_csv(
"/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline/data/processed/customer_churn_cleaned.csv"
)

In [57]:
import os

project_path = "/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline"

src_path = os.path.join(project_path, "src")

os.makedirs(src_path, exist_ok=True)

files = [
    "__init__.py",
    "data_loader.py",
    "preprocessing.py",
    "feature_engineering.py"
]

for file in files:
  file_path = os.path.join(src_path, file)
  if not os.path.exists(file_path):
    open(file_path, "w").close()

print("src folder and files created successfully")

src folder and files created successfully

In [58]:
import sys

project_path = "/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline"

if project_path not in sys.path:
  sys.path.append(project_path)

from src.data_loader import load_data

In [59]:
df = load_data(
    "/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline/data/processed/customer_churn_cleaned.csv"
)

df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [60]:
from src.feature_engineering import create_new_customer_feature

df = create_new_customer_feature(df)

df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,NewCustomer
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,No,No,One year,No,Mailed check,56.95,1889.50,No,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1

In [61]:
df["NewCustomer"].value_counts()

NewCustomer
0    4857
1    2175
Name: count, dtype: int64

In [69]:
from src.feature_engineering import create_tenure_group

df = create_tenure_group(df)

df["TenureGroup"].value_counts()

TenureGroup
49-72 Months    2239
0-12 Months     2175
25-48 Months    1594
13-24 Months    1024
Name: count, dtype: int64

In [77]:
import sys

# Delete the module from Python's internal cache if it exists
if 'src.feature_engineering' in sys.modules:
    del sys.modules['src.feature_engineering']
if 'src' in sys.modules:
    del sys.modules['src']

# Now re-import and check again
import src.feature_engineering as fe
print(dir(fe))

['__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', 'create_monthlyCharge_classifier', 'create_new_customer_feature', 'create_tenure_group', 'np', 'pd']

In [78]:
from src.feature_engineering import create_monthlyCharge_classifier

df = create_monthlyCharge_classifier(df)

df["HighMonthlyCharges"].value_counts()

HighMonthlyCharges
0    3519
1    3513
Name: count, dtype: int64

In [79]:
df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,NewCustomer,TenureGroup,HighMonthlyCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0-12 Months,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,One year,No,Mailed check,56.95,1889.50,No,0,25-48 Months,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0-12 Months,0
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,25-48 Months,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,0-12 Months,1

In [80]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7032 entries, 0 to 7031
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   gender              7032 non-null   object
 1   SeniorCitizen       7032 non-null   int64
 2   Partner             7032 non-null   object
 3   Dependents          7032 non-null   object
 4   tenure              7032 non-null   int64
 5   PhoneService        7032 non-null   object
 6   MultipleLines       7032 non-null   object
 7   InternetService     7032 non-null   object
 8   OnlineSecurity      7032 non-null   object
 9   OnlineBackup        7032 non-null   object
 10  DeviceProtection    7032 non-null   object
 11  TechSupport         7032 non-null   object
 12  StreamingTV         7032 non-null   object
 13  StreamingMovies     7032 non-null   object
 14  Contract            7032 non-null   object
 15  PaperlessBilling    7032 non-null   object
 16  PaymentMethod       7032 non-null   object
 17  MonthlyCharges      7032 non-null   float64
 18  TotalCharges        7032 non-null   float64
 19  Churn               7032 non-null   object
 20  NewCustomer         7032 non-null   int64
 21  TenureGroup         7032 non-null   category
 22  HighMonthlyCharges  7032 non-null   int64
dtypes: category(1), float64(2), int64(4), object(16)
memory usage: 1.2+ MB

In [81]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn', 'NewCustomer', 'TenureGroup',
       'HighMonthlyCharges'],
      dtype='object')

In [82]:
df.to_csv(
"/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline/data/processed/customer_churn_feature_engineered.csv",
index=False
)