<a href="https://colab.research.google.com/github/riyarvv/End-to-End-Customer-Churn-ML-Pipeline/blob/main/notebooks/10_Train_Test_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# End-to-End Customer Churn ML Pipeline

## Notebook 10 - Train Test Split

### Objective

Prepare the feature engineered dataset for machine learning by separating features and target variable, performing a train-test split, preventing data leakage, and saving reusable datasets.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

In [3]:
import sys

project_path="/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline"

if project_path not in sys.path:
  sys.path.append(project_path)

In [4]:
from src.data_loader import load_data

In [5]:
df = load_data("/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline/data/processed/customer_churn_feature_engineered.csv"
)

df.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,NewCustomer,TenureGroup,HighMonthlyCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,Month-to-month,Yes,Electronic check,29.85,29.85,No,1,0-12 Months,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,One year,No,Mailed check,56.95,1889.50,No,0,25-48 Months,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes,1,0-12 Months,0
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,No,One year,No,Bank transfer (automatic),42.30,1840.75,No,0,25-48 Months,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes,1,0-12 Months,1

In [6]:
df.columns

Index(['gender', 'SeniorCitizen', 'Partner', 'Dependents', 'tenure',
       'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity',
       'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV',
       'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod',
       'MonthlyCharges', 'TotalCharges', 'Churn', 'NewCustomer', 'TenureGroup',
       'HighMonthlyCharges'],
      dtype='object')

In [7]:
X=df.drop("Churn", axis=1)
y=df["Churn"]

In [8]:
X.head()

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,...,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,NewCustomer,TenureGroup,HighMonthlyCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,...,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,1,0-12 Months,0
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,...,No,No,One year,No,Mailed check,56.95,1889.50,0,25-48 Months,0
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,...,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,1,0-12 Months,0
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,...,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,0,25-48 Months,0
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,...,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,1,0-12 Months,1

In [9]:
y.head()

0     No
1     No
2    Yes
3     No
4    Yes
Name: Churn, dtype: object

In [10]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [11]:
X_train.shape

(5625, 22)

In [12]:
X_test.shape

(1407, 22)

In [13]:
print(y_train.shape)

(5625,)

In [14]:
y_test.shape

(1407,)

In [15]:
y_train.value_counts(normalize=True)

Churn
No     0.734222
Yes    0.265778
Name: proportion, dtype: float64

In [16]:
y_test.value_counts(normalize=True)

Churn
No     0.734186
Yes    0.265814
Name: proportion, dtype: float64

In [17]:
X_train,X_test,y_train,y_test=train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [18]:
y_train.value_counts(normalize=True)

Churn
No     0.734222
Yes    0.265778
Name: proportion, dtype: float64

In [19]:
X_train.to_csv(
"/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline/data/processed/X_train.csv",
index=False
)

X_train.to_csv(
"/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline/data/processed/X_train.csv",
index=False
)

y_train.to_csv(
"/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline/data/processed/y_train.csv",
index=False
)

y_test.to_csv(
"/content/drive/MyDrive/ML Projects/End-to-End-Customer-Churn-ML-Pipeline/data/processed/y_test.csv",
index=False
)

1. Why do we use stratify=y?  
To ensure that our training and testing datasets maintain the exact same proportion of target classes as the original dataset,

2. What is the purpose of X and y?  
X = input features
y = target variable

3. Why is data leakage dangerous?  
It secretly taints the training process by letting the model "cheat" or peek at the answers.

4. Why do we set random_state=42?  
Consistent results and fair comparison.